
FROM node:20-bookworm-slim

WORKDIR /usr/src/app

COPY package*.json .

RUN npm install

COPY . .

ARG NODE_ENV
ARG PORT
ARG DATABASE_URI
ARG CLOUDINARY_URL
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_CLOUD_API_KEY
ARG CLOUDINARY_CLOUD_API_SECRET
ARG CLOUDINARY_PROFILE_PUBLIC_ID
ARG DEFAULT_AVATAR_NAME

ENV NODE_ENV ${NODE_ENV} \
    PORT ${PORT} \
    DATABASE_URI ${DATABASE_URI} \
    CLOUDINARY_URL ${CLOUDINARY_URL} \
    CLOUDINARY_CLOUD_NAME ${CLOUDINARY_CLOUD_NAME} \ 
    CLOUDINARY_CLOUD_API_KEY ${CLOUDINARY_CLOUD_API_KEY} \
    CLOUDINARY_CLOUD_API_SECRET ${CLOUDINARY_CLOUD_API_SECRET} \
    CLOUDINARY_PROFILE_PUBLIC_ID ${CLOUDINARY_PROFILE_PUBLIC_ID} \
    DEFAULT_AVATAR_NAME ${DEFAULT_AVATAR_NAME}

EXPOSE 5000

CMD ["npm", "start"]