version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URI: ${DATABASE_URI}
      CLOUDINARY: ${CLOUDINARY}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_PROFILE_PUBLIC_ID: ${CLOUDINARY_PROFILE_PUBLIC_ID}
      DEFAULT_AVATAR_NAME: ${DEFAULT_AVATAR_NAME}
    ports:
      - 80:5000

