name: CI/CD

on:
    push:
        branches: ['main', 'test']

jobs:
    build-and-push-to-docker-hub:
        name: 'Build and Push Image to Docker Hub'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Build Image and Push to Docker Hub
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: ${{secrets.DOCKERHUB_USERNAME}}/todolist:latest
                  secrets: |
                      GIT_AUTH_TOKEN=${{secrets.GIT_AUTH_TOKEN}}

    deploy-to-linode:
        name: 'Connect to Linode through SSH and deploy the fresh image'
        runs-on: ubuntu-latest
        needs: build-and-push-to-docker-hub

        steps:
            - name: 'Connect to VPC'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.HOST}}
                  port: ${{secrets.PORT}}
                  username: ${{secrets.USERNAME}}
                  password: ${{secrets.PASSWORD}}
                  script: bash deploy.sh
